---
# tasks file for cache
- name: copy Cache templates
  template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
     mode: "{{ item.mode }}"
  loop:
     - { src: "templates/cachebackuplist", dest: "/tmp/cachebackuplist", mode: "0744" }
     - { src: "templates/cacherestore", dest: "/tmp/cacherestore", mode: "0744" }

- name: Copy Cache backup
  copy:
     src: files/cache.cbk
     dest: /var/opt/cache.cbk
     owner: root
     group: root
     mode: 0444


- name: "Build Cache namespaces"
  file:
     path: "{{ item }}"
     state: "directory"
     owner: "{{ cusr }}"
     group: "{{ cgrp }}"
  with_items:
      - "{{ Directories }}"

- name: "Run the Cache restore script"
  command: "/tmp/cacherestore"

- name: copy Cache config file
  template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: "{{ manusr }}"
     group: "{{ mangrp }}"
     mode: "{{ item.mode }}"
  loop:
     - { src: "templates/cache.cpf", dest: "/usr/local/cache/cache.cpf", mode: "0744" }

  notify:
    - Reload the systemd service daemon
    - restart cache
 
- name: Restart Cache once more
  service:
     name: "cache"
     state: "restarted"

